### ISSUE TITLE
Enchance Q0 metadata

### ISSUE THREAD

**Issue by juansensio** [earthpulse/eotdl#112]
When ingesting Q0 datasets, enforce the following metadata:
- author(s)
- license
- source link

Let's discuss on which fields should be required in this thread.

**Comment by patrick-griffiths** [comment]
@juansensio here are a few more essentials also for Q0 datasets: 
- uploader (this should only be visible to users who are logged in)
- geographic scope (will be inferred automatically later, I guess?) 
      --> this should be supported with a simple map view showing the bounding box of the geo scope
- temporal scope
- data use "how to use" (optional) 

How about enabling a "comments" section below, where users can exchange on datasets and encountered issues?
