### ISSUE TITLE
user stories & tracking

### ISSUE THREAD

**Issue by patrick-griffiths** [earthpulse/eotdl#117]
@dmoglioni @jamesemwheeler @juansensio 

as discussed in ESRIN, it is important to start defining user stories, to ensure that we track related requirements during the development. 

An example would be: 
A user builds a feature engineering workflow in openEO platform and then uses that workflow (openEO process graph) in EOTDL for training a model, then again later the process graph is reused for inference in the CDSE environment.  

@juansensio Where should we define and track such user stories?

**Comment by juansensio** [comment]
Doing so here, as separate issues, is a good option. 

We can discuss on them, derive the necessary developmenets, track the status and create additional isues if necessary.

This is definitely the way forward after v1 release.

Let's proceed like that if it works for you.

**Comment by dmoglioni** [comment]
USER STORY - notebook/ingestion/timeseries/versioning/data provenance

A user codes a script or notebook that generates a datasets as an output (e.g. timeseries) and then wants to ingest both data and source code (versioned) in EOTDL.

**Comment by patrick-griffiths** [comment]
User story: how to expose EuroCrops at granular level, so that queries such as extracting all Winter Wheat Parcels in a AOI can be performed..

**Comment by juansensio** [comment]
Thanks for the contribution, but please post your user stories as separe individual issues so we can track them individually  :)
