### ISSUE TITLE
Progress bar does not update on dataset download

### ISSUE THREAD

**Issue by robmarkcole** [earthpulse/eotdl#128]
The file **is** downloading yet the bar is at zero:

<img width="562" alt="image" src="https://github.com/earthpulse/eotdl/assets/11855322/d0d2dc10-d15e-4c82-bad1-4cd6dd31f2db">

**Comment by robmarkcole** [comment]
Possibly for zip file datasets only..

**Comment by juansensio** [comment]
Version 1 of EuroSAT-STAC is just 1 zip file, the bar will complete once that one file is downloaded.

If you try to download a dataset with multiple files, like https://www.eotdl.com/datasets/EuroSAT-RGB you will see the progress bar.

We could add one progress bar for small files and additional bars for large files to track the progress for both, is this what you are looking for?

**Comment by robmarkcole** [comment]
That sounds great
