### ISSUE TITLE
FR load defaults from .env file

### ISSUE THREAD

**Issue by robmarkcole** [earthpulse/eotdl#130]
It would be nice to use a `.env` file and avoid passing `path="data"` every time. Recommend https://pypi.org/project/python-dotenv/

**Comment by robmarkcole** [comment]
OK I see the default is `.cache` - the env var could be used to set this to another location

**Comment by juansensio** [comment]
You can set the `EOTDL_DOWNLOAD_PATH` to provide a default download path https://www.eotdl.com/docs/datasets/download

If this is not enough we can explore how to set it with a .ev file.
