### ISSUE TITLE
Created dates in UI not showing correct data

### ISSUE THREAD

**Issue by juansensio** [earthpulse/eotdl#140]
The Creation dates of datasets/models in the UI is not correct, some issue regarding the creation date may be happening.

**Comment by earthpulse** [comment]
Maybe a problem with the date set in the production environment?

**Comment by achtsnits** [comment]
do you have an example? for us it shows "Created 3 months ago" and similar...

**Comment by juansensio** [comment]
I will upload a dataset and share in Discord the dates.

**Comment by achtsnits** [comment]
created shows some day offset, updated seems to be correct?!?

**Comment by juansensio** [comment]
It looks like so... the code that creates a dataset can be found [here](https://github.com/earthpulse/eotdl/blob/main/api/api/src/usecases/datasets/create_dataset.py).

As you can see, the creation date is not set and it is using the default value set by pydantic [here](https://github.com/earthpulse/eotdl/blob/main/api/api/src/models/dataset.py).

Again, running the API locally works just fine but for some reason in the production environment there is that offset. Any ideas?

**Comment by achtsnits** [comment]
we just checked

there is no shift - it obviously uses the startup time of the process (at the moment 15d ago)

<img width="160" alt="image" src="https://github.com/earthpulse/eotdl/assets/54577319/bbab281c-6928-4111-8157-40e523e2d37e">

**Comment by achtsnits** [comment]
`createdAt: datetime = datetime.now()` is not correct in https://github.com/earthpulse/eotdl/blob/main/api/api/src/models/dataset.py

see https://stackoverflow.com/questions/71512035/how-should-i-specify-default-values-on-pydantic-fields-with-validate-always-to/71512493#71512493

thanks @totycro for example

**Comment by juansensio** [comment]
Thanks. Changes are applied and working fine.
