### ISSUE TITLE
Improve file explorer

### ISSUE THREAD

**Issue by juansensio** [earthpulse/eotdl#146]
Improve file explorer in models/datasets pages for better UX. Show additional information such as file size, checksum, version, etc.

**Comment by warmasster** [comment]
Hi, the chechksum is bigger than the file explorer width, a possible solution is to make it clickable as a button to copy it to the clipboard and put only some characters of the checksum in the explorer itself. do you want me to do it like this?

**Comment by earthpulse** [comment]
Maybe we can use an icon, when the user hovers over the icon it shows the checksum. I don't think enabling the copy to clipboard provides any additional value.

Another option is to show it only once a file is clicked (either in the preview if avialable or directly in the file explorer). Similar to how it is done here https://beta.source.coop/fused/overture/2024-03-12-alpha-0/

**Comment by warmasster** [comment]
I need the API to show the size of the files for the details section of each file. Also to make the preview it would need some way to access the content of the file.
