### ISSUE TITLE
Add dataset upgrade button in UI

### ISSUE THREAD

**Issue by juansensio** [earthpulse/eotdl#152]
Q0 and Q1 datasets should have a button on their page linking to a notebook in the user's workspace showing how to upgrade it to Q1 and Q2, respectively.

**Comment by juansensio** [comment]
@achtsnits how can we do this? Right now I have to open my workspace, go to the EOTDL notebook catalog and search for the notebook (03 q1 datasets, for example). Can we have a direct link to the notebooks in the catalog so we can redirect from the UI ?

**Comment by juansensio** [comment]
In the mean time I am using the "search" funcionality, with links like this "https://notebooks.api.eotdl.com/?search=notebook_name"

![Captura de pantalla 2024-02-15 a las 11 40 24](https://github.com/earthpulse/eotdl/assets/80452283/ed8f9168-c173-4aac-b70e-9e41ecb90a35)

**Comment by achtsnits** [comment]
so you mean to directly open a page like this
https://hub.api.eotdl.com/services/eoxhub-gateway/eotdl/notebook-view/notebooks/03_q1_datasets.ipynb

**Comment by juansensio** [comment]
Yes, thank. Can I use that url structure?

**Comment by achtsnits** [comment]
is there a way to make it easily configurable so that you don't have to release?

in general I'm fine with the url so we can keep that stable

**Comment by juansensio** [comment]
_is there a way to make it easily configurable so that you don't have to release?_

Let's talk about this on Discord.

I am closing this issue with the solution provided to directly open the notebook in the workspace.

**Comment by dmoglioni** [comment]
We were checking the approach to the datasets quality enhancement and we'd like to investigate with you an approach (on top of the provided notebook) to streamline the procedure and possibly link it to a remuneration mechanism to stimulate users contribution. Let's coordinate via mail to set up a call next week to discuss about it, thank you! @earthpulse @juansensio
