### ISSUE TITLE
Parametrized inference notebooks

### ISSUE THREAD

**Issue by juansensio** [earthpulse/eotdl#156]
Create parametrized notebooks for inference.

Requires generic Q1+ models wrappers.

**Comment by Schpidi** [comment]
similar to #154

**Comment by juansensio** [comment]
I will prepare some example notebooks (similar to training) and share to include in the workspace

**Comment by juansensio** [comment]
First iteration here https://github.com/earthpulse/eotdl/blob/develop/tutorials/notebooks/09_inference_template.ipynb

The only parameter should be the name of the model, however since different models will perform different tasks, it is not easy to suplly examples of inputs/outputs for all of them in the notebooks.

Alternatives would include adding links to sample data in the model's STAC metadata, and use them in the notebook if they are found.

**Comment by achtsnits** [comment]
- [ ] update workspace image with latest eotdl version
- [ ] publish new tutorial notebooks
