### ISSUE TITLE
Q1+ models STAC extension

### ISSUE THREAD

**Issue by fmariv** [earthpulse/eotdl#162]
Create a new STAC extension for Q1+ models ingested in EOTDL. 

ML Model spec
Name | Description | STAC Support | Actions
-- | -- | -- | --
Id | Unique id of the model | Core | -
dataset | Link to datasets used for training (preferably on EOTDL). | No | ML Model extension
Version | Version of the model | No | ML Model extension
Hparams | List of hyperparmeters used for training the model (including feature extraction pipeline if necessary) | No | ML Model extension
Type | Neural network, SVM, RF, … | No | ML Model extension
Features | Link to the feature store used to train the model (if required) | No | ML Feature extension
DOI |   | Scientific extension | -
Citation |   | Scientific extension | -
Inputs | Links to sample inputs for trying the model, pre-processing steps (pipeline) and other aspects such as normalization statistics, inputs names, etc. | No | ML Model extension
Outputs | List of output names, type, tasks, post-processing steps (pipeline) and other relevant aspects. | No | ML Model extension

**Comment by juansensio** [comment]
First example here https://github.com/earthpulse/eotdl/blob/main/tutorials/notebooks/05_q2_model.ipynb

Full support for ingesting/staging in CLI & API
