### ISSUE TITLE
UX enhancements: link to cloud workspace in portal top menu

### ISSUE THREAD

**Issue by Patrick1G** [earthpulse/eotdl#164]
@juansensio As a first step to make the EOTDL portal UX more present and tools less hidden, 
could we move the link to the EOxHub workspace (https://hub.api.eotdl.com/) to the top menu as indicated in screenshot below? (call it "cloud workspace"?):: 

![image](https://github.com/earthpulse/eotdl/assets/40148967/0f0fde00-ab4a-4ae8-9d33-b929ca71a72c)

**Comment by juansensio** [comment]
Yes, we will also add dedicated buttons to redirect to specific apps in the workspace (training, labelling, etc).

**Comment by juansensio** [comment]
New nav bar with links to cloud workspace and applications page (+ some icons)

![Captura de pantalla 2024-02-15 a las 10 09 29](https://github.com/earthpulse/eotdl/assets/80452283/49a3f2e5-d2b4-4e0d-b9c5-49529d8ccac0)
