### ISSUE TITLE
Train a model that Patrick suggested related to GDA APP: Satellite Road Segmentation

### ISSUE THREAD

**Issue by tatimars** [earthpulse/eotdl#169]
Train a model that Patrick suggested related to GDA APP,
Link to GitHub:
[https://github.com/aavek/Satellite-Image-Road-Segmentation/tree/main]

**Comment by Patrick1G** [comment]
@tatimars  any progress on this? 
We should add Judith to this github (I cant tag her)

**Comment by tatimars** [comment]
@Patrick1G Tasks with higher priority are currently underway, delaying the start of this one. We anticipate beginning in a couple or 3 of weeks. Once Judith provides me her username, I'll add her to this GitHub.

**Comment by juansensio** [comment]
Dataset ingested to EOTDL: https://www.eotdl.com/datasets/DeepGlobeRoadExtraction

and code for training implemented: https://github.com/earthpulse/pytorchEO/blob/main/examples/road_segmentation.ipynb

I'll ingest the model once the training ends.
