### ISSUE TITLE
Error when copying command from the models webpage

### ISSUE THREAD

**Issue by fmariv** [earthpulse/eotdl#170]
When you click the CLI command to download a model, from its model page, and copy it to a CLI, instead of being copied as `eotdl models [...]` it is copied as `eotdl datasets [. ..]`. The expected behavior is for it to be copied with the `models` command. Attached screenshot of the element where the commands are copied.

<img width="458" alt="Screenshot 2024-03-12 at 09 46 41" src="https://github.com/earthpulse/eotdl/assets/41595271/30c2b976-85c1-4699-a1d2-1ab4ac285f05">

## Current behaviour

```
$ eotdl datasets [...]
```
## Expected behaviour
```
$ eotdl models [...]
```

**Comment by juansensio** [comment]
Solved.
