### ISSUE TITLE
data ingestion through UI

### ISSUE THREAD

**Issue by tatimars** [earthpulse/eotdl#177]
Revive UI for data ingestion, in addition to command line ingestion

  - more convenient for editing markup

**Comment by juansensio** [comment]
Need to think how to do this effectively, suggestions are welcome

**Comment by Patrick1G** [comment]
This is how earthnets does it, a mask with user provided information plus a URL to the files: 
https://earthnets.nicepage.io/Datasets.html 

Generally, CLI ingestion should be recommended for large and complex datasets...

**Comment by juansensio** [comment]
Enable data ingestion through UI:

- limit number of files and size
- limited to Q0 datasets/models
