### ISSUE TITLE
add tutorials section in UI

### ISSUE THREAD

**Issue by juansensio** [earthpulse/eotdl#178]
Add a new page with direct links to the examples and tutorials on the cloud workspace.

**Comment by juansensio** [comment]
We have to define 2 sections:

1 - **Workshops**: one card/link per workshop on https://github.com/earthpulse/eotdl/tree/main/tutorials/workshops
You can put some placeholder text and I will complete it with the correct information. We will use the logos/screenshots of the conferences as the images (again, put some placeholder, I will get the final images)

2 - **Tutorials**: here we will have subsections:
    - datasets
    - data access
    - STAC
    - (others that will be added in the future)

The list of links is in https://github.com/earthpulse/eotdl/tree/main/tutorials for each subsection (basically we have to replicate this README in the website). Use the EOTDL logo in the card image and a small description of what the notebooks does (again, you can leave some placeholder text and I will updated it).

**Comment by warmasster** [comment]
Only descriptions and Photos left on the tutorials section
