### ISSUE TITLE
track active users

### ISSUE THREAD

**Issue by juansensio** [earthpulse/eotdl#186]

**Comment by juansensio** [comment]
Enable metrics endpoints in API to report in prometheus.

@achtsnits please suggest 2-3 interesting metrics that we can track and instructions on how to call the metrics API, I can. then implement the calls with the appropriate payloads wherever necessary.

**Comment by achtsnits** [comment]
the public EOTDL Status Dashboard is located here https://eotdl.status.eox.at/

if needed we can also give you (or other dedicated users) access to the Grafana dashboards as shown in the last ESA meeting

**Comment by juansensio** [comment]
Thanks. I would like to know how to log and visualize metrics such as:

- number of registered/active users
- ingested datasets/models
- staged datasets/models

I know we are tracking the downloaded bytes, can we visualize this information as well in the dashboard?

**Comment by achtsnits** [comment]
just to understand - where do we want to visualize these additional metrics, in the Grafana reporting for "us" in the context of EOTDL project or also visible to the end-users (i.e. available via API so you can include on website)?

**Comment by juansensio** [comment]
@Patrick1G what is your opinion on this matter?

**Comment by Patrick1G** [comment]
additional metrics: 
- event tracking (clicks, interactions) to get some information on what users are using in EOTDL

As for where the report should be shown: 
it would be nice to have it on the platform visible for authorized users (consortium and selected partners/users)

**Comment by juansensio** [comment]
We can use google analytics or a similar service for that, @Schpidi you proposed an OS alternative, can you share it ?

**Comment by Schpidi** [comment]
> We can use google analytics or a similar service for that, @Schpidi you proposed an OS alternative, can you share it ?

We're using https://matomo.org (previously named piwik) and I know ESA is using it as well. 

For example, look at https://race.esa.int and search for requests to "nix.eox.at" in the Dev Tools to see how it works.

I could add another configuration for a new "Website" as it is called in matomo to try it out in the EOTDL pages. Just let me know.

**Comment by earthpulse** [comment]
ok let's move forward, let me know if we need to implement anything on the website or the API.

**Comment by Schpidi** [comment]
I added a website configuration to our matomo service with ID 14. Please find below the JavaScript Tracking Code to include in the EOTDL page:

```
<!-- Matomo -->
<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://nix.eox.at/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '14']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
```

There is a list of readily available integrations at https://matomo.org/integrate/ or just integrate above code directly. Further documentation is available at https://developer.matomo.org/guides/tracking-javascript-guide.

I'll create a login for you @juansensio and send it via email. Let me know if I should add anybody else.
