### ISSUE TITLE
Feature Engineering with OpenEO - Use Case 2

### ISSUE THREAD

**Issue by earthpulse** [earthpulse/eotdl#191]
use eotdl gpu for training and then openeo for inference (onnx is supported).

- openEO should get ML model from eotdl (for example, road segmentation)
- user should provide inference data
- exectue process in openeo backend

**Comment by juansensio** [comment]
Use case focused on online inference. 

Measure response time.

**Comment by juansensio** [comment]
we are centralizing openeo related issues, including this one, through https://github.com/earthpulse/eotdl/issues/190
