### ISSUE TITLE
Feature Engineering with OpenEO - backend connection

### ISSUE THREAD

**Issue by earthpulse** [earthpulse/eotdl#192]
Provide a default backend to abstract complexity

- choose backend (CDSE/OTC makes sense since eotdl is already running there)
- automate user auth at registration / T&C acceptance (like we do for SH, geodb and EOX)
- ensure a basic free volume of processing for users in free tier (and additional integration for paid users)

Keep option for experienced users to select their own backend (although they will need to manage their own credentials).

**Comment by juansensio** [comment]
we are centralizing openeo related issues, including this one, through https://github.com/earthpulse/eotdl/issues/190
