### ISSUE TITLE
Feature Engineering with OpenEO - library integration

### ISSUE THREAD

**Issue by earthpulse** [earthpulse/eotdl#193]
Integrate openEO python lib in eotdl

- use TDS in eotdl as inputs to openeo processing pipelines
- ingest outputs to eotdl as new TDS / features
- save processing graphs (STAC) to use at inference time

**Comment by juansensio** [comment]
we are centralizing openeo related issues, including this one, through https://github.com/earthpulse/eotdl/issues/190
