### ISSUE TITLE
openEO in EOTDL cloud workspace

### ISSUE THREAD

**Issue by Patrick1G** [earthpulse/eotdl#208]
We would like to start basic testing with openEO from EOTDL

Unfortunately the openeo library is not available in the EOTDL python kernel..
Could you make sure this becomes available? 

@Schpidi @juansensio 

![image](https://github.com/user-attachments/assets/8a9c0138-89b9-4c84-9c60-df57c1676cff)

**Comment by juansensio** [comment]
Sure, we will add this dependency on the next release.

**Comment by juansensio** [comment]
https://github.com/earthpulse/eotdl/issues/215
