### ISSUE TITLE
use different colors for tags

### ISSUE THREAD

**Issue by juansensio** [earthpulse/eotdl#217]
depending on the category, use a different color for the tags

**Comment by Patrick1G** [comment]
@juansensio Just came across a nice example of a platform where this is already done: 
https://boninabox.geobon.org/tools
![image](https://github.com/user-attachments/assets/0d199970-5cf5-46ab-9df5-9f40c4ba80f8)

**Comment by juansensio** [comment]
Can be checked at dev version -> https://eotdl-dev.vercel.app/

Colors are the same for each category, but we can choose whatever color we want to assign at tag level.

Please chare a list of preferred colors.
