### ISSUE TITLE
dataset thumbnail and header image

### ISSUE THREAD

**Issue by juansensio** [earthpulse/eotdl#218]
Pre-select a list of images to use as default for the datasets. Should be copyright free.

Potentially, group them into tags/categories to link with the tags/categories assigned to the dataset/model.

**Comment by earthpulse** [comment]
Check a first iteration at https://eotdl-dev.vercel.app/ and https://eotdl-dev.vercel.app/datasets

A default image between 3 is used if the dataset/model does not have an image thumbnail as part of its metadata (defined by user at ingestion time). 

@Patrick1G @D-A-Albrecht we need a llist of default images that we can use (copyright free, etc.)
