### ISSUE TITLE
metadata inheritance for datasets

### ISSUE THREAD

**Issue by Patrick1G** [earthpulse/eotdl#235]
In this example, a Q2 version of a model does not have any meta data visible. How can this be? 

Q0 version - with elaborate metadata: 
https://www.eotdl.com/models/RoadSegmentation/

Q2 version - no meta data visble at all: 
https://www.eotdl.com/models/RoadSegmentationQ2

I think this is an issue that needs to be resolved. Metadata as provided for Q0 should be passed on to Q1 or Q2...

**Comment by earthpulse** [comment]
At this moment the datasets are independent from the platform point of view.

We already have discussions looking into changing this here https://github.com/earthpulse/eotdl/issues/198
