### ISSUE TITLE
A global inventory of solar photovoltaic generating units - dataset

### ISSUE THREAD

**Issue by Patrick1G** [earthpulse/eotdl#50]
Name: A global inventory of solar photovoltaic generating units - dataset
Size: 80 BM
Source: Annotations derived from OSM,  WRI Global Database of Power Plants (https://www.wri.org/research/global-database-power-plants)
Technique: object detection
Application: Renewable Energy, Green Transition
AOI: global
Time Span: annotations for 2017 and 2018, predictions are made for end of 2018
License: Creative Commons Attribution 4.0 International
Download link: https://zenodo.org/record/5005868#.Y5x6nXbMKHs
References: 
https://www.nature.com/articles/s41586-021-03957-7
https://www.nature.com/articles/s41586-021-03957-7#Sec10
https://github.com/Lkruitwagen/solar-pv-global-inventory

**Comment by earthpulse** [comment]
https://www.eotdl.com/datasets/GlobalInventorySolarPhotovoltaic/
