### ISSUE TITLE
TAIGA - The Artificial Intelligence dataset for forest Geographical Applications

### ISSUE THREAD

**Issue by Patrick1G** [earthpulse/eotdl#55]
Well curated TDS on forest attributes in Finland. Comes with hyperspectral image chips. 

Forest Inventory data is well organised, translated and curated... Excellent pilot dataset for EOTLD: 
https://etsin.fairdata.fi/dataset/9d0e89aa-f81f-458d-a657-3f02edf9e61b/data

[ @juansensio not sure why I cant set the labels etc. but this should go in list of datasets/...  ] 

The dataset consists of a VNIR hyperspectral image, forest variable data, and the relevant metadata. The TAIGA data area are from the southern boreal zone of Finland, in the vicinity of Hyytiälä forestry field station (61deg50’44”N, 24deg17’10”E), mostly covered by managed boreal forests, agricultural fields and wetlands. The airborne hyperspectral data were recorded under clear skies with 0.7 m pixel size on 15 June 2017. The forestry data are based on the stand-wise forest resource information gathered and processed by the Finnish Forest Centre. The data are stored as geolocated rasters in ENVI format.

**Comment by earthpulse** [comment]
https://www.eotdl.com/datasets/TAIGA/
