### ISSUE TITLE
Inference API

### ISSUE THREAD

**Issue by juansensio** [earthpulse/eotdl#71]

**Comment by earthpulse** [comment]
Base code from GDA APP is ready, we need to discuss how to go forward with this.

**Comment by Patrick1G** [comment]
suggestion:
- deploy in EOTDL by default
- allow standard users to run inference for small data volumes (credits) 
- to run inference at scale, users should request NOR sponsoring or pay

**Comment by juansensio** [comment]
Every user will have the api deployed in their workspace and accessible through a proxy URL. Depending on the user profile, they will have access to more or less resources (memory, GPU, ...). 

All users will have cpu inference on their free workspace available. NoR sponsorship can be requested to upgrade user profile (and enable more advanced inference capabilities).

Does this sound ok? @Patrick1G

**Comment by achtsnits** [comment]
@juansensio similar to https://github.com/earthpulse/eotdl/issues/194#issuecomment-2163030318 we have now done the setup for the ml-inference endpoint for your user, i.e. you need to use/recreate a JupyterHub token and call something like

```python
import requests

url = f'https://hub.api.eotdl.com/services/eoxhub-gateway/eotdl/ml-inference/EuroSAT-RGB-Q2'

res = requests.post(url,  files={'image': (open(img_path, 'rb'))}, headers={'Authorization': 'Token <your JuptyerHub token>'})

if res.status_code != 200:
	print(res.json())
res.status_code
```

**Comment by achtsnits** [comment]
check if metadata for a model can be retrieved via HTTP on same endpoint (also upgrade ml-inference  to latest version)

**Comment by achtsnits** [comment]
@juansensio just tested with the ml-inference deployment in your user namespace and I got a json description response for the model

<img width="1432" alt="image" src="https://github.com/user-attachments/assets/f759e0f0-76e6-4ec8-a846-f037dabe2366">

note: I restarted the pod during testing process so I don't know if a new docker image came into place as tag=latest is currently used

Can you please retest yourself and also create a new tagged image (latest is 18 days ago, the last tagged one older than 3 month...)

**Comment by juansensio** [comment]
I pushed new images with tags, nevertheless if we can use the latest tag is ok.
